# Generated by Django 4.2.13 on 2024-08-24 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kidzslateapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Third_term_fee',
        ),
    ]
