# Generated by Django 4.2.13 on 2024-08-24 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kidzslateapp', '0003_alter_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
